version: '3.8'

services:
  postgres:
      image: postgres:latest
      container_name: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: 123
        POSTGRES_DB: crudjava
      ports:
        - "5432:5432"
  app-java:
    build: ./api/demo
    restart: always
    ports:
      - "8080:8080"
    environment:
      DATABASE_URL: jdbc:postgresql://postgres:5432/crudjava
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: 123
    depends_on:
      - postgres

  app-vue:
    build:
      context: ./src/java-crud
    container_name: app-vue
    environment:
      VITE_JAVA_API_URL: app-java
    ports:
      - "5173:80"
    depends_on:
      - app-java