# Use a imagem base do Node.js
FROM node:18

# Defina o diretório de trabalho
WORKDIR /app

# Copie os arquivos do projeto para o contêiner
COPY package*.json ./
COPY . .

# Instale as dependências
RUN npm install

# Construa a aplicação Vue.js
RUN npm run build

# Use a imagem base do Nginx para servir o conteúdo estático
FROM nginx:alpine

# Copie os arquivos construídos para o diretório do Nginx
COPY --from=0 /app/dist /usr/share/nginx/html

# Exponha a porta padrão do Nginx
EXPOSE 80

# Comando padrão do Nginx
CMD ["nginx", "-g", "daemon off;"]